BoxLayout:
    orientation: 'vertical'

    Label:
        text: app.result

    GridLayout:
        cols: 4

        Button:
            text: '1'
            on_press: app.handleNumberPress(1)
        
        Button:
            text: '2'
            on_press: app.handleNumberPress(2)
        
        Button:
            text: '3'
            on_press: app.handleNumberPress(3)
        
        Button:
            text: '+'
            on_press: app.handleOperatorPress('+')
        
        Button:
            text: '4'
            on_press: app.handleNumberPress(4)
        
        Button:
            text: '5'
            on_press: app.handleNumberPress(5)
        
        Button:
            text: '6'
            on_press: app.handleNumberPress(6)
        
        Button:
            text: '-'
            on_press: app.handleOperatorPress('-')
        
        Button:
            text: '7'
            on_press: app.handleNumberPress(7)
        
        Button:
            text: '8'
            on_press: app.handleNumberPress(8)
        
        Button:
            text: '9'
            on_press: app.handleNumberPress(9)
        
        Button:
            text: '*'
            on_press: app.handleOperatorPress('*')

        Button:
            text: '0'
            on_press: app.handleNumberPress(0)
        
        Button:
            text: '/'
            on_press: app.handleOperatorPress('/')
        
        Button:
            text: 'DEL'
            on_press: app.handleDeletePress()
        
        Button:
            text: '='
            on_press: app.handleResultPress()